### ISSUE TITLE
Talk about license

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/tidy-nlp-in-R-book#25]
[License](https://github.com/EmilHvitfeldt/tidy-nlp-in-R-book/blob/master/LICENSE) in repo is currently CC0, which does not have any attribution or non-commercial bits in it. As is, this would let somebody else take the book content and sell it themselves. We probably want to change this to something like [CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/3.0/us/).

**Comment by EmilHvitfeldt** [comment]
We reference the license at the beginning of the book https://github.com/EmilHvitfeldt/tidy-nlp-in-R-book/blob/a8547aa830a646c7a1a6e947cbb1db2d0c583058/index.Rmd#L27

So we just have to change the license file and description
