### ISSUE TITLE
Add sentence about assumed modeling experiance

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/tidy-nlp-in-R-book#29]
https://text-and-modeling-in-r.netlify.com/preface.html#who-is-this-book-for

It could be a rewording of "machine learning". 

Add a link to "if you don't have much experience with predictive modeling"

**Comment by juliasilge** [comment]
- Add link to my interactive course
- Add link to [Bradley Boehmke's new book](https://bradleyboehmke.github.io/HOML/)
