### ISSUE TITLE
Switch to new_session: yes?

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/tidy-nlp-in-R-book#31]
https://github.com/EmilHvitfeldt/tidy-nlp-in-R-book/blob/7741776c8ba56596e18991a16d782458676e3e88/_bookdown.yml#L1

If we switch this to `yes`, then each chapter will knit in a separate session, making each chapter stand alone more cleanly. Right now, the whole book gets pasted together and knit as one. Thoughts?

**Comment by EmilHvitfeldt** [comment]
I would approve of having each chapter knit in separate sessions. That way we don't get weird problems where objects are transferred unexpectedly.
