### ISSUE TITLE
Plots are not rendering

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/tidy-nlp-in-R-book#6]
I haven't gotten a chance to dig into what's going, but I think because of where the chapters are stored, knitr is writing the images somewhere that then the website can't find. Images are not rendering on the website, i.e. here:
https://emilhvitfeldt.github.io/tidy-nlp-in-R-book/stemming.html#compare-some-stemming-options

**Comment by EmilHvitfeldt** [comment]
I got it working! with the wonders of Netlity! https://text-and-modeling-in-r.netlify.com/stemming.html
