### ISSUE TITLE
Lots of princesses

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/tidy-nlp-in-R-book#7]
The end of https://emilhvitfeldt.github.io/tidy-nlp-in-R-book/stemming.html#compare-some-stemming-options includes a lot of duplicate rows. Is that intentional or an error?

<img width="664" alt="Screen Shot 2019-08-04 at 4 57 09 AM" src="https://user-images.githubusercontent.com/14034784/62423329-74969d00-b674-11e9-9da5-cc797b03b4a9.png">

**Comment by juliasilge** [comment]
Use `distinct()`
