### ISSUE TITLE
Linguistics for NLP practitioners

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/tidy-nlp-in-R-book#8]
https://faculty.washington.edu/ebender/100things-sem_prag.html
https://www.cl.cam.ac.uk/teaching/1314/L100/introling.pdf
https://medium.com/@ODSC/linguistics-in-nlp-why-so-complex-4fd1fb9873a3

**Comment by EmilHvitfeldt** [comment]
http://people.cs.georgetown.edu/cosc572/s19/04_ling.pdf

**Comment by juliasilge** [comment]
https://www.morganclaypool.com/doi/abs/10.2200/s00493ed1v01y201303hlt020

**Comment by EmilHvitfeldt** [comment]
https://twitter.com/rctatman/status/1181710807177949184

**Comment by juliasilge** [comment]
I believe these are all incorporated now.

**Comment by juliasilge** [comment]
Unless we want to try to make the argument, similar to Rachael, that language data is more complex and difficult to model than image data. I'm not sure we want to make such a strong claim but I am definitely open to... reopening.
